### ISSUE TITLE
corrupt display when mouse pointer moved to left side of screen

### ISSUE THREAD

**Issue by firexx** [JeffyCN/xorg-xserver#5]
when mouse pointer moved on the left side of screnn the screen right of Mouse pointer shifts on 1 pix to the right. I can provide video of this issue if you can't reproduce. This issue observed on kernel 4.19 and on your tag xorg-xserver 1.20.4_2021_03_15. Also older version have this issue.

**Comment by JeffyCN** [comment]
well, assuming you are using hardware cursor on rk356x, there's a knowing issue that some hardware drm planes doesn't like this kind of usage.

the newest vop2 driver has a workaround for that, by scaling the source images, so you would see a skinny cursor instead ;)
for more details, please contact hjc@rock-chips.com andy.yan@rock-chips.com

i also have a hacky solution for it: https://github.com/JeffyCN/drm-cursor

anyway, i'm closing this since i don't think it's a xserver issue :)

**Comment by firexx** [comment]
sorry for reactivating of this issue 
do you have the recipe for your https://github.com/JeffyCN/drm-cursor solution?

**Comment by JeffyCN** [comment]
> sorry for reactivating of this issue
> do you have the recipe for your https://github.com/JeffyCN/drm-cursor solution?

for xserver, you can ether use sw cursor(SWCursor true in xorg conf), or use this drm-cursor wrapper(still HW cursor):
https://github.com/JeffyCN/rockchip_mirrors/tree/debian/packages/arm64/libdrm-cursor

install the libdrm-cursor.so, then preload it by:
echo /usr/lib/*/libdrm-cursor.so.1 >> /etc/ld.so.preload

log file would be /var/log/drm-cursor.log
